name: "Continuous Integration"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    check-dependencies:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  coverage: none
                  tools: composer-require-checker, composer-unused

            - name: Install dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}

            - name: Composer Require Checker
              run: composer-require-checker

            - name: Composer Unused
              run: composer-unused --excludePackage=symfony/dependency-injection  --excludePackage=symfony/property-access

    php-cs-fixer:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}

            - name: PHP-CS-Fixer
              run: php vendor/bin/php-cs-fixer fix --dry-run --diff --no-ansi

    phpstan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}

            - name: PHPStan
              run: php vendor/bin/phpstan analyse

    rector:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}

            - name: RectorPHP
              run: php vendor/bin/rector process --dry-run

    phpunit:
        strategy:
            matrix:
                operating-system: [ 'ubuntu-latest' ]
                php-version: [ '8.1', '8.2', '8.3' ]

        runs-on: ${{ matrix.operating-system }}

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}

            - name: Test PHPUnit
              run: php vendor/bin/phpunit